// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoO6K89QWB8skOtG9Ah7Az2a3WL8zknNo',
    appId: '1:895833591393:web:375bbe5f3ae3d692636420',
    messagingSenderId: '895833591393',
    projectId: 'ecommerce-12924',
    authDomain: 'ecommerce-12924.firebaseapp.com',
    storageBucket: 'ecommerce-12924.appspot.com',
    measurementId: 'G-G6LYT6SLBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPx-lcEugsPlT17i3QXW6KFQZGaSzgafc',
    appId: '1:895833591393:android:0741752e99f9e078636420',
    messagingSenderId: '895833591393',
    projectId: 'ecommerce-12924',
    storageBucket: 'ecommerce-12924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1hGyvWfQIH2bBRCLTDu3Ie2PcUrZaTzA',
    appId: '1:895833591393:ios:ced0d303df35f42f636420',
    messagingSenderId: '895833591393',
    projectId: 'ecommerce-12924',
    storageBucket: 'ecommerce-12924.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1hGyvWfQIH2bBRCLTDu3Ie2PcUrZaTzA',
    appId: '1:895833591393:ios:6cb814dbbe45e7ff636420',
    messagingSenderId: '895833591393',
    projectId: 'ecommerce-12924',
    storageBucket: 'ecommerce-12924.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
